# Строка из 11 цифр начинающая на 7
import os
import re

PHONE_REGEX = re.compile(r'^7\d{10}$')
API_PREFIX = '/api'
PRODUCT_NAME_MIN_LENGTH = 3
PRODUCT_NAME_MAX_LENGTH = 128
INTEREST_RATE_DAILY_MIN_LENGTH = 1
INTEREST_RATE_DAILY_MAX_LENGTH = 64
PRODUCT_LIST_JSON_PATH = os.path.join(
    os.path.dirname(__file__),
    'product_list.json'
)
PIONEER_PHONE_NUMBER = '71231231231'
REPEATER_PHONE_NUMBER = '71111111111'
INCORRECT_LENGTH_PHONE = '123'
INCORRECT_FIRST_SYMBOL_PHONE = '81111111111'
INCORRECT_SYMBOL_PHONE = '7111111111a'
PHONE_JSON_FIELD_NAME = 'phone'
NULL_PHONE_NUMBER = None
EMPTY_PHONE_NUMBER = ''
NOT_STR_PHONE_NUMBER = int(REPEATER_PHONE_NUMBER)
