from common.constants import API_PREFIX

PIONEER_FLOW_TYPE = 'pioneer'
REPEATER_FLOW_TYPE = 'repeater'
PRODUCT_PREFIX = '/products'
API_PRODUCT_PATH = f'{API_PREFIX}{PRODUCT_PREFIX}'
INCORRECT_LENGTH_PHONE = '123'
INCORRECT_FIRST_SYMBOL_PHONE = '81111111111'
INCORRECT_SYMBOL_PHONE = '7111111111a'
PHONE_JSON_FIELD_NAME = 'phone'
PIONEER_PHONE_NUMBER = '71231231231'
FLOW_TYPE_JSON_FIELD_NAME = 'flow_type'
AVAILABLE_PRODUCTS_JSON_FIELD_NAME = 'available_products'
REPEATER_PHONE_NUMBER = '71111111111'
NULL_PHONE_NUMBER = None
EMPTY_PHONE_NUMBER = ''
NOT_STR_PHONE_NUMBER = int(REPEATER_PHONE_NUMBER)
